<?php
//using the core functions, check if the user is logged in
require_once '../settings/core.php';

//check if user is logged in
if(!isLoggedIn()){
    header("Location: ../login/login.php");
    exit();
}

//also check if the user is an admin
if(!isAdmin()){
    //if the user is not an admin, redirect to the login page
    header("Location: ../login/login.php");
    exit();
}

//include category controller for database operations
require_once '../controllers/category_controller.php';

//retrieve - display categories in the system
$categories=get_all_categories_ctr();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Category Management</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <link href="../css/index.css" rel="stylesheet">
    <style>
        body {
            background: linear-gradient(135deg, #f5f7fa 0%, #e8ecf1 100%);
            min-height: 100vh;
            padding: 40px 20px;
        }
        h1 {
            color: var(--gray-900);
            font-weight: 800;
        }
        .welcome-text {
            color: var(--gray-600);
            margin-bottom: 40px;
            font-size: 1.1rem;
        }
        .card {
            background: white;
            border: 1px solid var(--gray-200);
            border-radius: 16px;
            box-shadow: var(--shadow-md);
            margin-bottom: 30px;
            transition: all 0.3s ease;
        }
        .card:hover {
            box-shadow: var(--shadow-lg);
            transform: translateY(-2px);
        }
        .card-header {
            background: linear-gradient(135deg, var(--primary) 0%, var(--primary-light) 100%);
            color: white;
            border-radius: 16px 16px 0 0 !important;
            padding: 20px 24px;
            border: none;
        }
        .card-header h3 {
            margin: 0;
            font-size: 1.3rem;
            font-weight: 600;
        }
        .card-body {
            padding: 24px;
        }
        .table thead {
            background: var(--gray-50);
        }
        .table thead th {
            color: var(--gray-700);
            font-weight: 600;
            border-bottom: 2px solid var(--gray-200);
        }
        .navigation-buttons {
            margin-top: 40px;
            display: flex;
            gap: 12px;
            flex-wrap: wrap;
        }
        .btn-primary {
            background: var(--primary);
            border: none;
            box-shadow: 0 4px 12px rgba(99, 102, 241, 0.3);
        }
        .btn-primary:hover {
            background: var(--primary-dark);
            box-shadow: 0 6px 16px rgba(99, 102, 241, 0.4);
        }
        .btn-warning {
            background: var(--accent);
            border: none;
            color: white;
        }
        .btn-warning:hover {
            background: #f97316;
            color: white;
        }
        .btn-danger {
            background: var(--danger);
            border: none;
        }
        .btn-danger:hover {
            background: #dc2626;
        }
        .btn-secondary {
            background: var(--gray-200);
            color: var(--gray-700);
            border: none;
        }
        .btn-secondary:hover {
            background: var(--gray-300);
            color: var(--gray-800);
        }
    </style>
</head>
<body>
    <div class="container mt-4">
        <h1>Category Management</h1>
        <p class="welcome-text">Welcome, <?php echo htmlspecialchars($_SESSION['user_name']); ?>!</p>

        <!-- CREATE - A form that takes the category's name (ID is autogenerated) -->
        <div class="row">
            <div class="col-md-6">
                <div class="card mb-4">
                    <div class="card-header">
                        <h3><i class="fa fa-plus"></i> Add New Category</h3>
                    </div>
                    <div class="card-body">
                        <form id="addCategoryForm">
                            <div class="mb-3">
                                <label for="categoryName" class="form-label">Category Name</label>
                                <input type="text" class="form-control" id="categoryName" name="category_name" required>
                                <div class="form-text">Category names must be unique.</div>
                            </div>
                            <button type="submit" class="btn btn-primary">Add Category</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <!-- RETRIEVE - Display categories in the system -->
        <div class="card">
            <div class="card-header">
                <h3><i class="fa fa-list"></i> Categories</h3>
            </div>
            <div class="card-body">
                <div id="categoriesContainer">
                    <?php if(empty($categories)): ?>
                        <p>No categories found. Add your first category above.</p>
                    <?php else: ?>
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Category Name</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody id="categoryTableBody">
                                <?php foreach($categories as $category): ?>
                                    <tr id="category_<?php echo $category['cat_id']; ?>">
                                        <td><?php echo htmlspecialchars($category['cat_id']); ?></td>
                                        <td class="category-name"><?php echo htmlspecialchars($category['cat_name']); ?></td>
                                        <td>
                                            <!-- UPDATE - Display style collects updated values. Only the name is editable, not the ID -->
                                            <button class="btn btn-sm btn-warning edit-btn"
                                                onclick="editCategory(<?php echo $category['cat_id']; ?>, '<?php echo htmlspecialchars($category['cat_name']); ?>')">
                                                Edit
                                            </button>
                                            <!-- DELETE - Delete a category -->
                                            <button class="btn btn-sm btn-danger delete-btn"
                                                onclick="deleteCategory(<?php echo $category['cat_id']; ?>, '<?php echo htmlspecialchars($category['cat_name']); ?>')">
                                                Delete
                                            </button>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    <?php endif; ?>
                </div>
            </div>
        </div>

        <div class="navigation-buttons">
            <a href="../index.php" class="btn btn-secondary">Back to Home</a>
            <a href="../login/logout.php" class="btn btn-outline-danger">Logout</a>
        </div>
    </div>

    <!-- UPDATE Modal - Only name is editable, not the ID -->
    <div class="modal fade" id="editCategoryModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Edit Category</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form id="editCategoryForm">
                    <div class="modal-body">
                        <!-- ID is not editable -->
                        <input type="hidden" id="editCategoryId" name="category_id">
                        <div class="mb-3">
                            <label class="form-label">Category ID</label>
                            <input type="text" class="form-control" id="displayCategoryId" disabled>
                            <div class="form-text">ID cannot be changed</div>
                        </div>
                        <!-- Only the name is editable -->
                        <div class="mb-3">
                            <label for="editCategoryName" class="form-label">Category Name</label>
                            <input type="text" class="form-control" id="editCategoryName" name="category_name" required>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary">Save Changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Alert Messages Container -->
    <div id="alertContainer" style="position: fixed; top: 20px; right: 20px; z-index: 1060;"></div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="../js/category.js"></script>
</body>
</html>